Drop database if exists movieLibrary;
Create database movieLibrary;

--1
CREATE TABLE ACTOR(
ACTID NUMBER(3),
ACTNAME VARCHAR(20),
ACTGENDER CHAR(1),
PRIMARY KEY (ACTID));

DESC ACTOR;

--2
CREATE TABLE DIRECTOR(
DIRID NUMBER(3),
DIRNAME VARCHAR(20),
DIRPHONE NUMBER(10),
PRIMARY KEY (DIRID));

DESC DIRECTOR;

--3
CREATE TABLE MOVIES(
MOVID NUMBER(4),
MOVTITLE VARCHAR(25),
MOVYEAR NUMBER(4),
MOVLANG VARCHAR(12),
DIRID NUMBER(3),
PRIMARY KEY (MOVID),
FOREIGN KEY (DIRID) REFERENCES DIRECTOR(DIRID));

DESC MOVIES;


--4
CREATE TABLE MOVIECAST(
ACTID NUMBER(3),
MOVID NUMBER(4),
ROLE VARCHAR(10),
PRIMARY KEY (ACTID,MOVID),
FOREIGN KEY (ACTID) REFERENCES ACTOR(ACTID),
FOREIGN KEY (MOVID) REFERENCES MOVIES(MOVID));

DESC MOVIECAST;

--5
CREATE TABLE RATING(
MOVID NUMBER(3),
REVSTARS VARCHAR(25),
PRIMARY KEY(MOVID),
FOREIGN KEY (MOVID) REFERENCES MOVIES(MOVID));

DESC RATING;

--1
INSERT INTO ACTOR VALUES(301,'?','F');
INSERT INTO ACTOR VALUES(302,'?','M');
INSERT INTO ACTOR VALUES(303,'?','M');
INSERT INTO ACTOR VALUES(304,'?','M');

SELECT * FROM ACTOR;

--2
INSERT INTO DIRECTOR VALUES(60,'?',9191919191);
INSERT INTO DIRECTOR VALUES(61,'?',818181818);
INSERT INTO DIRECTOR VALUES(62,'?',7171717171);
INSERT INTO DIRECTOR VALUES(63,'?',6161616161);

SELECT * FROM DIRECTOR;

--3
INSERT INTO MOVIES VALUES(1001,'?',2017,'?',60);
INSERT INTO MOVIES VALUES(1002,'?',2015,'?',60);
INSERT INTO MOVIES VALUES(1003,'?',2008,'?',61);
INSERT INTO MOVIES VALUES(1004,'?',2011,'?',63);

SELECT * FROM MOVIES;


